---
server:
  port: 9999

config:
  authserver:
    access-token:ttl: 2
    client-id: postman
    client-secret: postman-secret
    header:
      login-id: X_LOGIN_ID
      tracing-id: X_TRACING_ID

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
    